### ISSUE TITLE
Keep change log / history  of a property

### ISSUE THREAD

**Issue by ayushin** [lvm/django-eav2#237]
It would be great is something like https://github.com/jazzband/django-simple-history API was supported for properties, so that it would be possible to keep track over the property changes over time.

Any ideas how to implement that?

**Comment by Dresdn** [comment]
Hi @ayushin - Good news is that [django-simple-history can track the history for 3rd party modules](https://django-simple-history.readthedocs.io/en/latest/quick_start.html#track-history-for-a-third-party-model) already, so hooking it up to the Attribute model is pretty simple.

To your point about adding APIs, I would say the 3rd party tracking app would be the one to hook into Django to gather history, so not sure there'd be anything to do here.

Open to any ideas you may have otherwise!
